[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.module]
source = 'src/libs/nativefs.lua'
before = 'main.lua'
name = 'handy/nativefs'

# Init
[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["index.lua"]

# Resolving mod path
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.run()'''
position = "before"
payload = '''
Handy_main_file_path = "{{lovely_hack:patch_dir}}"
'''
match_indent = true
overwrite = false
