[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Modules

[[patches]]
[patches.module]
source = 'modules/utils.lua'
before = 'main.lua'
name = 'handy/utils'

[[patches]]
[patches.module]
source = 'modules/config.lua'
before = 'main.lua'
name = 'handy/config'

[[patches]]
[patches.module]
source = 'modules/fake_events.lua'
before = 'main.lua'
name = 'handy/fake_events'

[[patches]]
[patches.module]
source = 'modules/controller.lua'
before = 'main.lua'
name = 'handy/controller'

[[patches]]
[patches.module]
source = 'modules/presets.lua'
before = 'main.lua'
name = 'handy/presets'

[[patches]]
[patches.module]
source = 'modules/ui/index.lua'
before = 'main.lua'
name = 'handy/ui'

[[patches]]
[patches.module]
source = 'modules/ui/state_panel.lua'
before = 'main.lua'
name = 'handy/ui/state_panel'

[[patches]]
[patches.module]
source = 'modules/ui/functions.lua'
before = 'main.lua'
name = 'handy/ui/functions'

[[patches]]
[patches.module]
source = 'modules/ui/parts.lua'
before = 'main.lua'
name = 'handy/ui/parts'

[[patches]]
[patches.module]
source = 'modules/ui/config_tabs.lua'
before = 'main.lua'
name = 'handy/ui/config_tabs'

[[patches]]
[patches.module]
source = 'modules/ui/config.lua'
before = 'main.lua'
name = 'handy/ui/config'

# Controls

[[patches]]
[patches.module]
source = 'modules/controls/presets_switch.lua'
before = 'main.lua'
name = 'handy/controls/presets_switch'

[[patches]]
[patches.module]
source = 'modules/controls/insta_cash_out.lua'
before = 'main.lua'
name = 'handy/controls/insta_cash_out'

[[patches]]
[patches.module]
source = 'modules/controls/insta_booster_skip.lua'
before = 'main.lua'
name = 'handy/controls/insta_booster_skip'

[[patches]]
[patches.module]
source = 'modules/controls/deselect_hand.lua'
before = 'main.lua'
name = 'handy/controls/deselect_hand'

[[patches]]
[patches.module]
source = 'modules/controls/show_deck_preview.lua'
before = 'main.lua'
name = 'handy/controls/show_deck_preview'

[[patches]]
[patches.module]
source = 'modules/controls/regular_keybinds.lua'
before = 'main.lua'
name = 'handy/controls/regular_keybinds'

[[patches]]
[patches.module]
source = 'modules/controls/insta_highlight.lua'
before = 'main.lua'
name = 'handy/controls/insta_highlight'

[[patches]]
[patches.module]
source = 'modules/controls/insta_highlight_entire_f_hand.lua'
before = 'main.lua'
name = 'handy/controls/insta_highlight_entire_f_hand'

[[patches]]
[patches.module]
source = 'modules/controls/insta_actions.lua'
before = 'main.lua'
name = 'handy/controls/insta_actions'

[[patches]]
[patches.module]
source = 'modules/controls/move_highlight.lua'
before = 'main.lua'
name = 'handy/controls/move_highlight'

[[patches]]
[patches.module]
source = 'modules/controls/speed_multiplier.lua'
before = 'main.lua'
name = 'handy/controls/speed_multiplier'

[[patches]]
[patches.module]
source = 'modules/controls/nopeus_interaction.lua'
before = 'main.lua'
name = 'handy/controls/nopeus_interaction'

[[patches]]
[patches.module]
source = 'modules/controls/not_just_yet_interaction.lua'
before = 'main.lua'
name = 'handy/controls/not_just_yet_interaction'

[[patches]]
[patches.module]
source = 'modules/controls/animation_skip.lua'
before = 'main.lua'
name = 'handy/controls/animation_skip'

[[patches]]
[patches.module]
source = 'modules/controls/dangerous_actions.lua'
before = 'main.lua'
name = 'handy/controls/dangerous_actions'

# Init

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["index.lua"]
